print(f"Lab06_1\n")
a = int(input(f"Please enter your score : "))
b = int(input(f"Please enter your score : "))
c = int(input(f"Please enter your score : "))
d = int(input(f"Please enter your score : "))
e = int(input(f"Please enter your score : "))
f = int(input(f"Please enter your score : "))
g = int(input(f"Please enter your score : "))
h = int(input(f"Please enter your score : "))
i = int(input(f"Please enter your score : "))
j = int(input(f"Please enter your score : "))
sum = a+b+c+d+e+f+g+h+i+j
average = sum /10
print(f"Score 1 : ",{a})
print(f"Score 2 : ",{b})
print(f"Score 3 : ",{c})
print(f"Score 4 : ",{d})
print(f"Score 5 : ",{e})
print(f"Score 6 : ",{f})
print(f"Score 7 : ",{g})
print(f"Score 8 : ",{h})
print(f"Score 9 : ",{i})
print(f"Score 10 : ",{j})
print(f"total score : {sum}")
print(f"Average score : {average}")